name: mindmitra
description: MindMitra - AI-powered mental health support app for youth.
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  fl_chart: ^0.68.0
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  uuid: ^4.5.1
  lottie: ^3.1.2
  shimmer: ^3.0.0
  confetti: ^0.7.0
  http: ^1.2.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
